### ISSUE TITLE
useReplicant doesn't support namespaces

### ISSUE THREAD

**Issue by tedkulp** [Hoishin/use-nodecg#1]
nodecg.Replicant has a 2nd optional parameter for namespace.  Unfortunately, the bundle I'm working with uses it exclusively.  See: https://nodecg.com/NodeCG.html#Replicant

I did make a quick version of `useReplicantNS` as a workaround, but would rather get something into your main repository.  I didn't know if maybe adding it to the options and taking it out if it exists is better for your API than making a whole new method.

I'm willing to make and submit the change, but I didn't want to do extra work that you might want to do differently anyway.

Thanks.  Great work so far!

**Comment by Hoishin** [comment]
Easy and simple API would be accepting an object as second argument of `useReplicant`.
It could be the same API as original NodeCG one, but it would require function type overload and lots of type guard.
Having another hook is not ideal to me.

You are more than welcome to make PRs 😄

**Comment by tedkulp** [comment]
Sounds great, thanks.  I'll try to get that out to you today.
